# Generated by Django 3.1.7 on 2021-03-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20210317_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(default='CTF', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(default='OyuSec', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='prize',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='rule',
            field=models.TextField(default=''),
        ),
    ]
