# Generated by Django 3.1.7 on 2021-03-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20210318_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='prize',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('coming', 'coming'), ('archive', 'archive'), ('live', 'live')], default='coming', max_length=100, verbose_name='Status'),
        ),
    ]
