# Generated by Django 3.1.7 on 2021-03-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20210318_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='rating',
            field=models.PositiveIntegerField(default=20, verbose_name='Rating'),
        ),
    ]
