# Generated by Django 3.1.7 on 2021-03-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competition_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='competitionuser',
            name='score',
        ),
        migrations.AddField(
            model_name='competition',
            name='weight',
            field=models.PositiveIntegerField(default=20, verbose_name='Weight'),
        ),
    ]
