# Generated by Django 3.1.7 on 2021-03-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20210324_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='weight',
            field=models.FloatField(default=20.0, verbose_name='Weight'),
        ),
    ]
