# Generated by Django 3.1.7 on 2021-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_competitionuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionuser',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='competitionuser',
            name='score',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Score'),
        ),
    ]
