# Generated by Django 3.1.7 on 2021-03-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_auto_20210324_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionuser',
            name='place',
            field=models.PositiveIntegerField(default=0, verbose_name='Place'),
        ),
    ]
