# Generated by Django 3.1.7 on 2021-03-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuserprofile',
            name='fblood',
            field=models.PositiveIntegerField(default=0, verbose_name='First blood'),
        ),
    ]
