COMPETITION_UPCOMING = 'upcoming'
COMPETITION_ARCHIVE = 'archive'
COMPETITION_LIVE = 'live'

COMPETITION_STATUS_CHOICES = (
    (COMPETITION_UPCOMING, 'upcoming'),
    (COMPETITION_ARCHIVE, 'archive'),
    (COMPETITION_LIVE, 'live')
)
