AUTHENTICATION_REQUIRED = "Authentication required"
ACCESS_DENIED = "You dont have access to this resource"
SUCCESS_UPDATED = "Амжилттай шинэчлэлээ"
SUCCESS_ADD = "Амжилттай нэмэгдлээ"
SUCCESS_DELETED = "Амжилттай хасагдлаа"
